"use client";

import { useState, useEffect, useCallback } from "react";
import { X, Package, RefreshCw, Wand2, Tag, Plus, Trash2, Layers, Pencil, Check, AlertTriangle, ExternalLink, GitBranch, Percent } from "lucide-react";
import Link from "next/link";
import { useProducts } from "@/providers/ProductsProvider";
import { useAuth } from "@/providers/AuthProvider";
import { useFlows } from "@/providers/FlowsProvider";
import type { Product, ProductVariant } from "@/types/product";
import type { Flow } from "@/types/flow";
import { generateUniqueCode as generateUniqueCodeBase, attrSignature } from "@/lib/stock-utils";

const STOCK_TOOL_IDS = new Set(["get_stock", "reserve_stock"]);

function findStockFlows(flows: Flow[]): Flow[] {
  return flows.filter((flow) =>
    flow.nodes.some(
      (node) =>
        node.type === "toolcall" &&
        STOCK_TOOL_IDS.has((node.data as Record<string, unknown>).tool as string)
    )
  );
}

interface ProductModalProps {
  isOpen: boolean;
  onClose: () => void;
  editingProduct?: Product | null;
}

type ModalTab = "general" | "variants";

const inputClasses =
  "w-full rounded-lg border border-slate-600 bg-slate-800/50 px-4 py-2.5 text-white text-sm placeholder-slate-500 focus:border-[#dd7430] focus:ring-2 focus:ring-[#dd7430]/20 focus:outline-none";

const errorClasses =
  "w-full rounded-lg border border-red-500 bg-slate-800/50 px-4 py-2.5 text-white text-sm placeholder-slate-500 focus:border-red-400 focus:ring-2 focus:ring-red-500/20 focus:outline-none";

// ── Helpers ──────────────────────────────────────────────────────────────────

function generateUniqueCode(excludeId?: string | null, allProducts?: Product[]): string {
  const skus = (allProducts ?? []).filter((p) => p.id !== excludeId).map((p) => p.sku);
  return generateUniqueCodeBase(skus);
}


// ── Form state ────────────────────────────────────────────────────────────────

interface VariantFormItem {
  id: string;
  attributes: Record<string, string>;
  sku: string;
  price: string;
}

interface FormState {
  name: string;
  sku: string;
  description: string;
  brand: string;
  model: string;
  price: string;
  stock: string;
  unit: string;
  category: string;
  variantTypeIds: string[];
  variants: VariantFormItem[];
  discountIds: string[];
}

interface FormErrors {
  name?: string;
  sku?: string;
  brand?: string;
  model?: string;
  price?: string;
  stock?: string;
}

const EMPTY_FORM: FormState = {
  name: "",
  sku: "",
  description: "",
  brand: "",
  model: "",
  price: "",
  stock: "",
  unit: "",
  category: "",
  variantTypeIds: [],
  variants: [],
  discountIds: [],
};

function productToForm(p: Product): FormState {
  return {
    name: p.name,
    sku: p.sku,
    description: p.description,
    brand: p.brand ?? "",
    model: p.model ?? "",
    price: p.price > 0 ? String(p.price) : "",
    stock: p.stock > 0 ? String(p.stock) : "",
    unit: p.unit,
    category: p.category,
    variantTypeIds: p.variantTypeIds ?? [],
    discountIds: p.discountIds ?? [],
    variants: (p.variants ?? []).map((v) => ({ id: v.id, attributes: v.attributes, sku: v.sku ?? "", price: v.price != null && v.price > 0 ? String(v.price) : "" })),
  };
}

// ── Component ─────────────────────────────────────────────────────────────────

export function ProductModal({ isOpen, onClose, editingProduct }: ProductModalProps) {
  const { products, variantTypes, discounts, addProduct, updateProduct } = useProducts();
  const { user } = useAuth();
  const { flows } = useFlows();

  const [activeTab, setActiveTab] = useState<ModalTab>("general");
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [errors, setErrors] = useState<FormErrors>({});
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  // New variant inline form state
  const [newAttrs, setNewAttrs] = useState<Record<string, string>>({});
  const [newVariantSku, setNewVariantSku] = useState("");
  const [newVariantPrice, setNewVariantPrice] = useState("");
  const [newVariantError, setNewVariantError] = useState<string | null>(null);

  // Edit variant state
  const [editingVariantId, setEditingVariantId] = useState<string | null>(null);
  const [editAttrs, setEditAttrs] = useState<Record<string, string>>({});
  const [editVariantSku, setEditVariantSku] = useState("");
  const [editVariantPrice, setEditVariantPrice] = useState("");
  const [editVariantError, setEditVariantError] = useState<string | null>(null);

  // Delete variant confirmation state
  const [confirmDeleteVariantId, setConfirmDeleteVariantId] = useState<string | null>(null);
  const [variantBlockingFlows, setVariantBlockingFlows] = useState<Flow[]>([]);

  const genCode = useCallback(
    () => generateUniqueCode(editingProduct?.id, products),
    [products, editingProduct?.id]
  );

  useEffect(() => {
    if (!isOpen) return;
    setActiveTab("general");
    setNewAttrs({});
    setNewVariantSku("");
    setNewVariantPrice("");
    setNewVariantError(null);
    setEditingVariantId(null);
    setEditAttrs({});
    setEditVariantSku("");
    setEditVariantPrice("");
    setEditVariantError(null);
    setConfirmDeleteVariantId(null);
    setVariantBlockingFlows([]);
    if (editingProduct) {
      setForm(productToForm(editingProduct));
      setIsAutoGenerated(false);
    } else {
      const code = genCode();
      setForm({ ...EMPTY_FORM, sku: code });
      setIsAutoGenerated(true);
    }
    setErrors({});
  }, [isOpen, editingProduct]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── General field handlers ──────────────────────────────────────────────────

  const handleRegenerate = () => {
    setForm((prev) => ({ ...prev, sku: genCode() }));
    setIsAutoGenerated(true);
    setErrors((prev) => ({ ...prev, sku: undefined }));
  };

  const handleSkuChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsAutoGenerated(false);
    setForm((prev) => ({ ...prev, sku: e.target.value }));
    if (errors.sku) setErrors((prev) => ({ ...prev, sku: undefined }));
  };

  const set =
    (field: keyof Omit<FormState, "sku" | "variantTypeIds" | "variants">) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setForm((prev) => ({ ...prev, [field]: e.target.value }));
      if (field in errors) setErrors((prev) => ({ ...prev, [field]: undefined }));
    };

  // ── Variant type selection ──────────────────────────────────────────────────

  const toggleVariantType = (vtId: string) => {
    setForm((prev) => {
      const isSelected = prev.variantTypeIds.includes(vtId);
      if (isSelected) {
        // Deselect: remove from ids and strip matching attribute from variants
        const vt = variantTypes.find((v) => v.id === vtId);
        const newVariants = vt
          ? prev.variants.filter((variant) => !(vt.key in variant.attributes))
          : prev.variants;
        return { ...prev, variantTypeIds: prev.variantTypeIds.filter((id) => id !== vtId), variants: newVariants };
      }
      return { ...prev, variantTypeIds: [...prev.variantTypeIds, vtId] };
    });
    setNewAttrs({});
    setNewVariantError(null);
  };

  // ── Discount selection ──────────────────────────────────────────────────────

  const toggleDiscount = (discountId: string) => {
    setForm((prev) => ({
      ...prev,
      discountIds: prev.discountIds.includes(discountId)
        ? prev.discountIds.filter((id) => id !== discountId)
        : [...prev.discountIds, discountId],
    }));
  };

  // ── Variant management ──────────────────────────────────────────────────────

  const selectedVariantTypes = variantTypes.filter((vt) => form.variantTypeIds.includes(vt.id));

  const handleAddVariant = () => {
    setNewVariantError(null);

    // Validate: all type values filled
    const missing = selectedVariantTypes.filter((vt) => !newAttrs[vt.key]?.trim());
    if (missing.length > 0) {
      setNewVariantError(`Completá: ${missing.map((vt) => vt.name).join(", ")}.`);
      return;
    }

    // Build canonical attrs
    const attrs: Record<string, string> = {};
    selectedVariantTypes.forEach((vt) => { attrs[vt.key] = newAttrs[vt.key].trim(); });

    // Duplicate check
    const sig = attrSignature(attrs);
    const isDuplicate = form.variants.some((v) => attrSignature(v.attributes) === sig);
    if (isDuplicate) {
      setNewVariantError("Ya existe una variante con esa combinación de atributos.");
      return;
    }

    setForm((prev) => ({
      ...prev,
      variants: [
        ...prev.variants,
        { id: crypto.randomUUID(), attributes: attrs, sku: newVariantSku.trim(), price: newVariantPrice.trim() },
      ],
    }));
    setNewAttrs({});
    setNewVariantSku("");
    setNewVariantPrice("");
  };

  const handleRemoveVariant = (variantId: string) => {
    setForm((prev) => ({ ...prev, variants: prev.variants.filter((v) => v.id !== variantId) }));
  };

  // ── Edit variant handlers ────────────────────────────────────────────────────

  const startEditVariant = (variant: VariantFormItem) => {
    setConfirmDeleteVariantId(null);
    setVariantBlockingFlows([]);
    setEditingVariantId(variant.id);
    setEditAttrs({ ...variant.attributes });
    setEditVariantSku(variant.sku);
    setEditVariantPrice(variant.price);
    setEditVariantError(null);
  };

  const cancelEditVariant = () => {
    setEditingVariantId(null);
    setEditVariantError(null);
  };

  const handleSaveVariantEdit = (variantId: string) => {
    const missing = selectedVariantTypes.filter((vt) => !editAttrs[vt.key]?.trim());
    if (missing.length > 0) {
      setEditVariantError(`Completá: ${missing.map((vt) => vt.name).join(", ")}.`);
      return;
    }
    const attrs: Record<string, string> = {};
    selectedVariantTypes.forEach((vt) => { attrs[vt.key] = editAttrs[vt.key].trim(); });
    const sig = attrSignature(attrs);
    const isDuplicate = form.variants.some((v) => v.id !== variantId && attrSignature(v.attributes) === sig);
    if (isDuplicate) {
      setEditVariantError("Ya existe una variante con esa combinación de atributos.");
      return;
    }
    setForm((prev) => ({
      ...prev,
      variants: prev.variants.map((v) =>
        v.id === variantId ? { ...v, attributes: attrs, sku: editVariantSku.trim(), price: editVariantPrice.trim() } : v
      ),
    }));
    setEditingVariantId(null);
    setEditVariantError(null);
  };

  // ── Delete variant handlers ──────────────────────────────────────────────────

  const requestDeleteVariant = (variantId: string) => {
    setEditingVariantId(null);
    const blocking = findStockFlows(flows);
    setConfirmDeleteVariantId(variantId);
    setVariantBlockingFlows(blocking);
  };

  const handleConfirmDeleteVariant = () => {
    if (confirmDeleteVariantId && variantBlockingFlows.length === 0) {
      handleRemoveVariant(confirmDeleteVariantId);
    }
    setConfirmDeleteVariantId(null);
    setVariantBlockingFlows([]);
  };

  // ── Submit ──────────────────────────────────────────────────────────────────

  const validate = (): boolean => {
    const next: FormErrors = {};
    if (!form.name.trim()) next.name = "El nombre es obligatorio.";
    if (!form.brand.trim()) next.brand = "La marca es obligatoria.";
    if (!form.model.trim()) next.model = "El modelo es obligatorio.";

    const trimmedSku = form.sku.trim();
    if (!trimmedSku) {
      next.sku = "El código es obligatorio.";
    } else {
      const duplicate = products.find(
        (p) => p.sku.toLowerCase() === trimmedSku.toLowerCase() && p.id !== editingProduct?.id
      );
      if (duplicate) next.sku = `El código "${trimmedSku}" ya está en uso.`;
    }

    if (form.price !== "" && (isNaN(Number(form.price)) || Number(form.price) < 0))
      next.price = "El precio debe ser un número mayor o igual a 0.";
    if (form.stock !== "" && (!Number.isInteger(Number(form.stock)) || Number(form.stock) < 0))
      next.stock = "El stock debe ser un número entero mayor o igual a 0.";

    setErrors(next);
    if (Object.keys(next).length > 0) setActiveTab("general");
    return Object.keys(next).length === 0;
  };

  const buildVariants = (now: string): ProductVariant[] =>
    form.variants.map((v) => ({
      id: v.id,
      attributes: v.attributes,
      sku: v.sku || undefined,
      price: v.price !== "" && !isNaN(Number(v.price)) && Number(v.price) >= 0 ? Number(v.price) : undefined,
      createdAt: editingProduct?.variants?.find((ev) => ev.id === v.id)?.createdAt ?? now,
    }));

  const handleSubmit = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!validate()) return;

    const now = new Date().toISOString();
    const updatedBy = user ? { id: user.id, name: user.name } : undefined;
    const common = {
      name: form.name.trim(),
      sku: form.sku.trim(),
      description: form.description.trim(),
      brand: form.brand.trim(),
      model: form.model.trim(),
      price: form.price !== "" ? Number(form.price) : 0,
      stock: form.stock !== "" ? Math.round(Number(form.stock)) : 0,
      unit: form.unit.trim(),
      category: form.category.trim(),
      variantTypeIds: form.variantTypeIds,
      discountIds: form.discountIds,
      variants: buildVariants(now),
    };

    if (editingProduct) {
      updateProduct(editingProduct.id, { ...common, updatedBy });
    } else {
      addProduct(common);
    }
    onClose();
  };

  if (!isOpen) return null;

  // ── Render ──────────────────────────────────────────────────────────────────

  const tabBtn = (tab: ModalTab, label: string, badge?: number) => (
    <button
      key={tab}
      type="button"
      onClick={() => setActiveTab(tab)}
      className={`flex items-center gap-1.5 px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px ${
        activeTab === tab
          ? "border-[#dd7430] text-white"
          : "border-transparent text-slate-400 hover:text-slate-200"
      }`}
    >
      {label}
      {badge !== undefined && badge > 0 && (
        <span className="rounded-full bg-[#dd7430]/20 px-1.5 py-0.5 text-xs text-[#dd7430] font-semibold">
          {badge}
        </span>
      )}
    </button>
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} aria-hidden="true" />

      <div className="relative z-10 flex max-h-[92vh] w-full max-w-lg flex-col rounded-xl border border-slate-700 bg-slate-900 shadow-2xl">
        {/* Header */}
        <div className="flex shrink-0 items-center justify-between border-b border-transparent px-6 pt-4 pb-0">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-[#dd7430]/10 border border-[#dd7430]/20">
              <Package className="size-5 text-[#dd7430]" />
            </div>
            <h2 className="text-lg font-semibold text-white">
              {editingProduct ? "Editar producto" : "Nuevo producto"}
            </h2>
          </div>
          <button onClick={onClose} className="mb-2 text-slate-400 hover:text-white transition-colors" aria-label="Cerrar">
            <X className="size-5" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex shrink-0 gap-1 border-b border-slate-700 px-6">
          {tabBtn("general", "Datos generales")}
          {tabBtn("variants", "Variantes", form.variants.length)}
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} noValidate className="flex min-h-0 flex-1 flex-col">
          <div className="flex-1 overflow-y-auto px-6 py-5">

            {/* ── Tab: Datos generales ── */}
            {activeTab === "general" && (
              <div className="space-y-5">
                {/* Nombre */}
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-300">
                    Nombre <span className="text-red-400">*</span>
                  </label>
                  <input
                    type="text"
                    value={form.name}
                    onChange={set("name")}
                    placeholder="Ej: Camiseta"
                    className={errors.name ? errorClasses : inputClasses}
                    autoFocus
                  />
                  {errors.name && <p className="mt-1 text-xs text-red-400">{errors.name}</p>}
                </div>

                {/* Marca | Modelo */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="mb-1.5 block text-sm font-medium text-slate-300">
                      Marca <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={form.brand}
                      onChange={set("brand")}
                      placeholder="Ej: Michelin"
                      className={errors.brand ? errorClasses : inputClasses}
                    />
                    {errors.brand && <p className="mt-1 text-xs text-red-400">{errors.brand}</p>}
                  </div>
                  <div>
                    <label className="mb-1.5 block text-sm font-medium text-slate-300">
                      Modelo <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={form.model}
                      onChange={set("model")}
                      placeholder="Ej: Energy Saver"
                      className={errors.model ? errorClasses : inputClasses}
                    />
                    {errors.model && <p className="mt-1 text-xs text-red-400">{errors.model}</p>}
                  </div>
                </div>

                {/* Código */}
                <div>
                  <div className="mb-1.5 flex items-center gap-2">
                    <label className="text-sm font-medium text-slate-300">
                      Código <span className="text-red-400">*</span>
                    </label>
                    {isAutoGenerated && (
                      <span className="flex items-center gap-1 rounded-full bg-[#dd7430]/10 border border-[#dd7430]/20 px-2 py-0.5 text-xs text-[#dd7430]">
                        <Wand2 className="size-3" />
                        Autogenerado
                      </span>
                    )}
                  </div>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={form.sku}
                      onChange={handleSkuChange}
                      placeholder="Ej: CAM-001"
                      className={`flex-1 font-mono ${errors.sku ? errorClasses : inputClasses}`}
                    />
                    {!editingProduct && (
                      <button
                        type="button"
                        onClick={handleRegenerate}
                        className="flex shrink-0 items-center gap-1.5 rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800/50 hover:text-white transition-colors"
                        aria-label="Regenerar código"
                      >
                        <RefreshCw className="size-4" />
                        <span className="hidden sm:inline">Regenerar</span>
                      </button>
                    )}
                  </div>
                  {errors.sku ? (
                    <p className="mt-1 text-xs text-red-400">{errors.sku}</p>
                  ) : (
                    <p className="mt-1 text-xs text-slate-500">
                      {isAutoGenerated ? "Código autogenerado — podés editarlo." : "Debe ser único."}
                    </p>
                  )}
                </div>

                {/* Descripción */}
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-300">
                    Descripción <span className="text-slate-500 font-normal">(opcional)</span>
                  </label>
                  <textarea
                    value={form.description}
                    onChange={set("description")}
                    placeholder="Ej: Camiseta de algodón, colores surtidos"
                    rows={2}
                    className={`${inputClasses} resize-none`}
                  />
                </div>

                {/* Datos adicionales */}
                <div className="border-t border-slate-700/60 pt-1">
                  <p className="mb-4 text-xs font-medium uppercase tracking-wider text-slate-500">
                    Datos adicionales
                  </p>
                  <div className="space-y-3">
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="mb-1.5 block text-sm font-medium text-slate-300">
                          Precio base <span className="text-slate-500 font-normal">(opc.)</span>
                        </label>
                        <input type="number" min="0" step="0.01" value={form.price} onChange={set("price")} placeholder="0.00" className={errors.price ? errorClasses : inputClasses} />
                        {errors.price && <p className="mt-1 text-xs text-red-400">{errors.price}</p>}
                      </div>
                      <div>
                        <label className="mb-1.5 block text-sm font-medium text-slate-300">
                          Stock <span className="text-slate-500 font-normal">(opc.)</span>
                        </label>
                        <input type="number" min="0" step="1" value={form.stock} onChange={set("stock")} placeholder="0" className={errors.stock ? errorClasses : inputClasses} />
                        {errors.stock && <p className="mt-1 text-xs text-red-400">{errors.stock}</p>}
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="mb-1.5 block text-sm font-medium text-slate-300">Unidad</label>
                        <input type="text" value={form.unit} onChange={set("unit")} placeholder="unidad, kg, lt" className={inputClasses} />
                      </div>
                      <div>
                        <label className="mb-1.5 block text-sm font-medium text-slate-300">Categoría</label>
                        <input type="text" value={form.category} onChange={set("category")} placeholder="Ropa, Bebidas…" className={inputClasses} />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Tipos de variante */}
                <div className="border-t border-slate-700/60 pt-1">
                  <p className="mb-3 text-xs font-medium uppercase tracking-wider text-slate-500">
                    Tipos de variante
                  </p>
                  {variantTypes.length === 0 ? (
                    <p className="text-xs text-slate-500">
                      No hay tipos de variante definidos.{" "}
                      <button type="button" className="text-[#dd7430] hover:underline" onClick={() => { onClose(); }}>
                        Creá uno primero.
                      </button>
                    </p>
                  ) : (
                    <div className="flex flex-wrap gap-2">
                      {variantTypes.map((vt) => {
                        const selected = form.variantTypeIds.includes(vt.id);
                        return (
                          <button
                            key={vt.id}
                            type="button"
                            onClick={() => toggleVariantType(vt.id)}
                            className={`flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
                              selected
                                ? "border-violet-500/40 bg-violet-500/10 text-violet-300"
                                : "border-slate-600 text-slate-400 hover:border-slate-500 hover:text-slate-300"
                            }`}
                          >
                            <Tag className="size-3" />
                            {vt.name}
                          </button>
                        );
                      })}
                    </div>
                  )}
                </div>

                {/* Descuentos aplicados */}
                <div className="border-t border-slate-700/60 pt-1">
                  <p className="mb-3 text-xs font-medium uppercase tracking-wider text-slate-500">
                    Descuentos aplicados
                  </p>
                  {discounts.length === 0 ? (
                    <p className="text-xs text-slate-500">
                      No hay descuentos definidos.{" "}
                      <button type="button" className="text-[#dd7430] hover:underline" onClick={() => { onClose(); }}>
                        Creá uno primero.
                      </button>
                    </p>
                  ) : (
                    <div className="space-y-3">
                      <div className="flex flex-wrap gap-2">
                        {discounts.map((d) => {
                          const selected = form.discountIds.includes(d.id);
                          return (
                            <button
                              key={d.id}
                              type="button"
                              onClick={() => toggleDiscount(d.id)}
                              className={`flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
                                selected
                                  ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300"
                                  : "border-slate-600 text-slate-400 hover:border-slate-500 hover:text-slate-300"
                              }`}
                            >
                              <Percent className="size-3" />
                              {d.name}
                              <span className={selected ? "text-emerald-400/70" : "text-slate-600"}>
                                {d.percentage % 1 === 0 ? d.percentage : d.percentage.toFixed(2)}%
                              </span>
                            </button>
                          );
                        })}
                      </div>
                      {(() => {
                        if (form.discountIds.length === 0 || form.price === "") return null;
                        const basePrice = Number(form.price);
                        if (isNaN(basePrice) || basePrice <= 0) return null;
                        const selectedDiscounts = discounts.filter((d) => form.discountIds.includes(d.id));
                        const totalPct = Math.min(100, selectedDiscounts.reduce((sum, d) => sum + d.percentage, 0));
                        const finalPrice = basePrice * (1 - totalPct / 100);
                        return (
                          <div className="flex items-center gap-2 rounded-lg border border-emerald-500/20 bg-emerald-500/5 px-3 py-2">
                            <Percent className="size-3.5 shrink-0 text-emerald-400" />
                            <span className="text-xs text-slate-400">
                              Precio estimado:{" "}
                              <span className="font-medium text-emerald-400">
                                $ {finalPrice.toLocaleString("es-AR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                              </span>
                              <span className="ml-1 text-slate-500">
                                (−{totalPct % 1 === 0 ? totalPct : totalPct.toFixed(2)}% sobre $ {basePrice.toLocaleString("es-AR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })})
                              </span>
                            </span>
                          </div>
                        );
                      })()}
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* ── Tab: Variantes ── */}
            {activeTab === "variants" && (
              <div className="space-y-4">
                {selectedVariantTypes.length === 0 ? (
                  <div className="flex flex-col items-center justify-center rounded-xl border border-slate-700 bg-slate-800/30 py-10 text-center">
                    <Layers className="size-10 text-slate-600 mb-3" />
                    <p className="text-sm font-medium text-white mb-1">Sin tipos de variante seleccionados</p>
                    <p className="text-xs text-slate-400 max-w-xs">
                      Seleccioná tipos de variante en la pestaña{" "}
                      <button type="button" className="text-[#dd7430] hover:underline" onClick={() => setActiveTab("general")}>
                        Datos generales
                      </button>{" "}
                      para empezar a agregar variantes.
                    </p>
                  </div>
                ) : (
                  <>
                    {/* Existing variants list */}
                    {form.variants.length > 0 && (
                      <ul className="space-y-2">
                        {form.variants.map((variant) => {
                          const isEditing = editingVariantId === variant.id;
                          const isConfirmingDelete = confirmDeleteVariantId === variant.id;

                          if (isEditing) {
                            return (
                              <li key={variant.id} className="rounded-lg border border-violet-500/40 bg-slate-800/60 px-4 py-3 space-y-3">
                                <div className="grid grid-cols-2 gap-2">
                                  {selectedVariantTypes.map((vt) => (
                                    <div key={vt.key}>
                                      <label className="mb-1 block text-xs font-medium text-slate-300">{vt.name}</label>
                                      <input
                                        type="text"
                                        value={editAttrs[vt.key] ?? ""}
                                        onChange={(e) => {
                                          setEditAttrs((prev) => ({ ...prev, [vt.key]: e.target.value }));
                                          setEditVariantError(null);
                                        }}
                                        className={inputClasses}
                                      />
                                    </div>
                                  ))}
                                </div>
                                <div className="grid grid-cols-2 gap-2">
                                  <div>
                                    <label className="mb-1 block text-xs font-medium text-slate-300">
                                      Código <span className="text-slate-500 font-normal">(opc.)</span>
                                    </label>
                                    <input
                                      type="text"
                                      value={editVariantSku}
                                      onChange={(e) => setEditVariantSku(e.target.value)}
                                      className={`font-mono ${inputClasses}`}
                                    />
                                  </div>
                                  <div>
                                    <label className="mb-1 block text-xs font-medium text-slate-300">
                                      Precio <span className="text-slate-500 font-normal">(opc.)</span>
                                    </label>
                                    <input
                                      type="number"
                                      min="0"
                                      step="0.01"
                                      value={editVariantPrice}
                                      onChange={(e) => setEditVariantPrice(e.target.value)}
                                      placeholder="0.00"
                                      className={inputClasses}
                                    />
                                  </div>
                                </div>
                                {editVariantError && (
                                  <p className="text-xs text-red-400">{editVariantError}</p>
                                )}
                                <div className="flex items-center gap-2 justify-end">
                                  <button
                                    type="button"
                                    onClick={cancelEditVariant}
                                    className="px-3 py-1.5 rounded-lg border border-slate-600 text-slate-300 text-xs font-medium hover:bg-slate-800/50 transition-colors"
                                  >
                                    Cancelar
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => handleSaveVariantEdit(variant.id)}
                                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-violet-600 text-white text-xs font-medium hover:bg-violet-700 transition-colors"
                                  >
                                    <Check className="size-3.5" />
                                    Guardar
                                  </button>
                                </div>
                              </li>
                            );
                          }

                          if (isConfirmingDelete) {
                            const isBlocked = variantBlockingFlows.length > 0;
                            return (
                              <li key={variant.id} className="rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3 space-y-3">
                                {isBlocked ? (
                                  <>
                                    <div className="flex items-start gap-2">
                                      <AlertTriangle className="size-4 text-amber-400 shrink-0 mt-0.5" />
                                      <p className="text-xs text-slate-300">
                                        No se puede eliminar: hay flujos con acciones de stock que podrían referenciar esta variante.
                                      </p>
                                    </div>
                                    <ul className="space-y-1 rounded-lg border border-slate-700 bg-slate-800/50 p-2">
                                      {variantBlockingFlows.map((flow) => (
                                        <li key={flow.id} className="flex items-center justify-between gap-2">
                                          <div className="flex items-center gap-1.5 min-w-0">
                                            <GitBranch className="size-3.5 shrink-0 text-slate-500" />
                                            <span className="truncate text-xs text-slate-300">{flow.name}</span>
                                          </div>
                                          <Link
                                            href={`/flows/${flow.id}`}
                                            className="flex shrink-0 items-center gap-1 text-xs text-[#dd7430] hover:underline"
                                            onClick={() => { setConfirmDeleteVariantId(null); onClose(); }}
                                          >
                                            <ExternalLink className="size-3" />
                                            Abrir
                                          </Link>
                                        </li>
                                      ))}
                                    </ul>
                                    <div className="flex justify-end">
                                      <button
                                        type="button"
                                        onClick={() => setConfirmDeleteVariantId(null)}
                                        className="px-3 py-1.5 rounded-lg bg-slate-700 text-slate-200 text-xs font-medium hover:bg-slate-600 transition-colors"
                                      >
                                        Entendido
                                      </button>
                                    </div>
                                  </>
                                ) : (
                                  <>
                                    <p className="text-xs text-slate-300">
                                      ¿Eliminar esta variante? Esta acción no se puede deshacer.
                                    </p>
                                    <div className="flex items-center gap-2 justify-end">
                                      <button
                                        type="button"
                                        onClick={() => setConfirmDeleteVariantId(null)}
                                        className="px-3 py-1.5 rounded-lg border border-slate-600 text-slate-300 text-xs font-medium hover:bg-slate-800/50 transition-colors"
                                      >
                                        Cancelar
                                      </button>
                                      <button
                                        type="button"
                                        onClick={handleConfirmDeleteVariant}
                                        className="px-3 py-1.5 rounded-lg bg-red-500/20 border border-red-500/30 text-red-400 text-xs font-medium hover:bg-red-500/30 transition-colors"
                                      >
                                        Eliminar
                                      </button>
                                    </div>
                                  </>
                                )}
                              </li>
                            );
                          }

                          return (
                            <li
                              key={variant.id}
                              className="flex items-center justify-between gap-3 rounded-lg border border-slate-700 bg-slate-800/40 px-4 py-3"
                            >
                              <div className="flex flex-wrap items-center gap-1.5 min-w-0">
                                {selectedVariantTypes.map((vt) =>
                                  variant.attributes[vt.key] ? (
                                    <span key={vt.key} className="rounded-full border border-violet-500/30 bg-violet-500/10 px-2 py-0.5 text-xs text-violet-300">
                                      {vt.name}: <span className="font-medium">{variant.attributes[vt.key]}</span>
                                    </span>
                                  ) : null
                                )}
                                {variant.sku && (
                                  <span className="font-mono rounded border border-slate-600 bg-slate-700/50 px-1.5 py-0.5 text-xs text-slate-400">
                                    {variant.sku}
                                  </span>
                                )}
                                {(() => {
                                  const hasOwn = variant.price !== "" && !isNaN(Number(variant.price)) && Number(variant.price) >= 0;
                                  const basePrice = form.price !== "" ? Number(form.price) : null;
                                  const effectivePrice = hasOwn ? Number(variant.price) : basePrice;
                                  if (effectivePrice === null) return null;
                                  return (
                                    <span className="text-xs text-emerald-400">
                                      $ {effectivePrice.toLocaleString("es-AR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                      {!hasOwn && <span className="ml-0.5 text-slate-500">(base)</span>}
                                    </span>
                                  );
                                })()}
                              </div>
                              <div className="flex shrink-0 items-center gap-1">
                                <button
                                  type="button"
                                  onClick={() => startEditVariant(variant)}
                                  className="p-1.5 rounded-md text-slate-500 hover:text-white hover:bg-slate-700 transition-colors"
                                  aria-label="Editar variante"
                                >
                                  <Pencil className="size-4" />
                                </button>
                                <button
                                  type="button"
                                  onClick={() => requestDeleteVariant(variant.id)}
                                  className="p-1.5 rounded-md text-slate-500 hover:text-red-400 hover:bg-red-500/10 transition-colors"
                                  aria-label="Eliminar variante"
                                >
                                  <Trash2 className="size-4" />
                                </button>
                              </div>
                            </li>
                          );
                        })}
                      </ul>
                    )}

                    {/* Add variant form */}
                    <div className="rounded-xl border border-slate-700/80 bg-slate-800/30 p-4 space-y-3">
                      <p className="text-xs font-medium text-slate-400 uppercase tracking-wider">
                        Agregar variante
                      </p>

                      {/* One input per selected variant type */}
                      <div className="grid grid-cols-2 gap-3">
                        {selectedVariantTypes.map((vt) => (
                          <div key={vt.key}>
                            <label className="mb-1.5 block text-xs font-medium text-slate-300">{vt.name}</label>
                            <input
                              type="text"
                              value={newAttrs[vt.key] ?? ""}
                              onChange={(e) => {
                                setNewAttrs((prev) => ({ ...prev, [vt.key]: e.target.value }));
                                setNewVariantError(null);
                              }}
                              placeholder={`Ej: ${vt.name === "Color" ? "Rojo" : vt.name === "Talle" ? "M" : "…"}`}
                              className={inputClasses}
                            />
                          </div>
                        ))}
                      </div>

                      {/* Optional variant SKU + price */}
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="mb-1.5 block text-xs font-medium text-slate-300">
                            Código <span className="text-slate-500 font-normal">(opc.)</span>
                          </label>
                          <input
                            type="text"
                            value={newVariantSku}
                            onChange={(e) => setNewVariantSku(e.target.value)}
                            placeholder="Ej: CAM-ROJO-M"
                            className={`font-mono ${inputClasses}`}
                          />
                        </div>
                        <div>
                          <label className="mb-1.5 block text-xs font-medium text-slate-300">
                            Precio <span className="text-slate-500 font-normal">(opc.)</span>
                          </label>
                          <input
                            type="number"
                            min="0"
                            step="0.01"
                            value={newVariantPrice}
                            onChange={(e) => setNewVariantPrice(e.target.value)}
                            placeholder="0.00"
                            className={inputClasses}
                          />
                        </div>
                      </div>

                      {newVariantError && (
                        <p className="text-xs text-red-400">{newVariantError}</p>
                      )}

                      <button
                        type="button"
                        onClick={handleAddVariant}
                        className="flex items-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium text-white hover:bg-violet-700 transition-colors"
                      >
                        <Plus className="size-4" />
                        Agregar
                      </button>
                    </div>
                  </>
                )}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex shrink-0 justify-end gap-3 border-t border-slate-700 px-6 py-4">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-lg border border-slate-600 text-slate-200 text-sm font-medium hover:bg-slate-800/50 transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="px-4 py-2 rounded-lg bg-[#dd7430] text-white text-sm font-medium hover:bg-orange-600 transition-colors"
            >
              {editingProduct ? "Guardar cambios" : "Crear producto"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
